/* ===== 리서치 상세 데이터 (위키 검증) =====
 * roster.js(PDF 전체 명단)에 병합될 상세 정보.
 * 병합 키: (seasonKey, nameKo) → 실패 시 nameKo 단독(접두어 제거) 매칭.
 * relations 의 id 는 리서치 당시 임시 id 이며, build-data.mjs 가 최종 id 로 재매핑한다.
 */
window.DETAILS = [
  /* ---------- 1기 감정 티니핑 ---------- */
  { id: "heartsping", nameKo: "하츄핑", seasonKey: "emotion", nameEn: "Heartsping", emotion: "사랑",
    traits: "1기의 대표 로열 티니핑으로, 주인공 이로미의 파트너 요정이다. 여러 형태로 변신할 수 있으며 사랑의 감정을 상징한다.",
    story: "감정 큐브를 지키던 로열 티니핑 중 하나로, 이로미와 만나 함께 흩어진 티니핑들을 잡으러 다닌다.",
    relations: [{ id: "lalaping", label: "동료" }, { id: "ajaping", label: "동료" }, { id: "baroping", label: "동료" }, { id: "chachaping", label: "동료" }, { id: "haeping", label: "동료" }], colorHex: "#F65C9A" },
  { id: "lalaping", nameKo: "라라핑", seasonKey: "emotion", nameEn: "Lalaping", emotion: "즐거움",
    traits: "즐거움과 행복을 상징하는 로열 티니핑으로 밝고 명랑한 성격이다.",
    story: "감정 큐브를 지키던 로열 티니핑 중 하나이다.",
    relations: [{ id: "heartsping", label: "동료" }], colorHex: "#F5A623" },
  { id: "ajaping", nameKo: "아자핑", seasonKey: "emotion", nameEn: "Gogoping", emotion: "의욕",
    traits: "'아자!' 하는 파이팅과 의욕을 상징하는 로열 티니핑으로 종종 스스로 마법 사고를 일으킨다.",
    story: "감정 큐브를 지키던 로열 티니핑 중 하나이다.",
    relations: [{ id: "heartsping", label: "동료" }], colorHex: "#E8503A" },
  { id: "baroping", nameKo: "바로핑", seasonKey: "emotion", nameEn: "Dadaping", emotion: "올바름",
    traits: "'바로!' 정확함과 올바름을 상징하는 로열 티니핑으로 원리원칙을 중시한다.",
    story: "감정 큐브를 지키던 로열 티니핑 중 하나로, 이후 로열 티니핑 스쿨의 교관 역할을 맡는다.",
    relations: [{ id: "heartsping", label: "동료" }], colorHex: "#3B7BD4" },
  { id: "chachaping", nameKo: "차차핑", seasonKey: "emotion", nameEn: "Chachaping", emotion: "여유",
    traits: "여유롭고 차분한 성격을 상징하는 로열 티니핑이다.",
    story: "감정 큐브를 지키던 로열 티니핑 중 하나로, 이후 다른 티니핑들을 가르치는 역할을 맡는다.",
    relations: [{ id: "heartsping", label: "동료" }], colorHex: "#9B7EDE" },
  { id: "haeping", nameKo: "해핑", seasonKey: "emotion", nameEn: "Happing", emotion: "기쁨",
    traits: "해맑은 웃음과 밝음을 상징하는 로열 티니핑이다.",
    story: "감정 큐브를 지키던 로열 티니핑 중 하나로, 후속 시즌에서 다시 주요 인물로 등장한다.",
    relations: [{ id: "heartsping", label: "동료" }], colorHex: "#FBC531" },
  { id: "roarping", nameKo: "화나핑", seasonKey: "emotion", nameEn: "Roarping", emotion: "분노",
    traits: "'화나다'에서 온 이름으로 분노의 감정을 상징한다. 쉽게 화를 내는 성격이다.",
    story: "1기에서 흩어진 감정 티니핑 중 하나로 등장하여 이로미와 하츄핑에게 붙잡힌다.",
    relations: [], colorHex: "#E23A2E" },
  { id: "nonoping", nameKo: "시러핑", seasonKey: "emotion", nameEn: "Nonoping", emotion: "거부",
    traits: "'싫어'에서 온 이름으로 무엇이든 거부하고 싫어하는 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#5BB98C" },
  { id: "spookping", nameKo: "무셔핑", seasonKey: "emotion", nameEn: "Spookping", emotion: "무서움",
    traits: "'무서워'에서 온 이름으로 두려움과 공포의 감정을 상징한다. 겁이 많다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#5B4B8A" },
  { id: "moseyping", nameKo: "차나핑", seasonKey: "emotion", nameEn: "Moseyping", emotion: "귀찮음",
    traits: "'귀찮아'에서 온 이름으로 만사가 귀찮은 나른한 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#9A8C6D" },
  { id: "shyping", nameKo: "부끄핑", seasonKey: "emotion", nameEn: "Shyping", emotion: "부끄러움",
    traits: "'부끄럽다'에서 온 이름으로 수줍음과 부끄러움의 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#F58AB0" },
  { id: "narrping", nameKo: "나르핑", seasonKey: "emotion", nameEn: "Narrping", emotion: "자아도취",
    traits: "'나르시시즘'에서 온 이름으로 자기 자신에게 도취되는 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#E0A93B" },
  { id: "artping", nameKo: "그림핑", seasonKey: "emotion", nameEn: "Artping", emotion: "예술",
    traits: "'그림'에서 온 이름으로 그림 그리기와 예술적 감성을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#A65BC2" },
  { id: "giggleping", nameKo: "악동핑", seasonKey: "emotion", nameEn: "Giggleping", emotion: "장난",
    traits: "'악동'에서 온 이름으로 짓궂은 장난기를 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#6BBF59" },
  { id: "aingping", nameKo: "아잉핑", seasonKey: "emotion", nameEn: "Aingping", emotion: "애교",
    traits: "'아잉' 하는 애교를 상징하는 티니핑으로, '애교의 티니핑'으로 불린다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#F79AC0" },
  { id: "sleepingp", nameKo: "코자핑", seasonKey: "emotion", nameEn: "Sleeping", emotion: "졸음",
    traits: "'코 자다'에서 온 이름으로 졸음과 잠의 감정을 상징한다. 늘 졸려한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#8CB8E0" },
  { id: "kikiping", nameKo: "키키핑", seasonKey: "emotion", nameEn: "Kikiping", emotion: "장난기",
    traits: "'키키' 하는 짓궂은 웃음과 장난기를 상징하는 티니핑이다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#C6D63D" },
  { id: "kkambakping", nameKo: "깜빡핑", seasonKey: "emotion", nameEn: "Kkambakping", emotion: "건망증",
    traits: "'깜빡하다'에서 온 이름으로 잘 잊어버리는 건망증을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#A9C7E0" },
  { id: "ttiyongping", nameKo: "띠용핑", seasonKey: "emotion", nameEn: "Ttiyongping", emotion: "놀람",
    traits: "'띠용' 하는 놀람의 감정을 상징하는 티니핑이다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#F2C531" },
  { id: "jureuping", nameKo: "주르핑", seasonKey: "emotion", nameEn: "Jureuping", emotion: "슬픔",
    traits: "'주르륵' 눈물이 흐르는 데서 온 이름으로 슬픔과 눈물의 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#5AA9E6" },
  { id: "mimicping", nameKo: "따라핑", seasonKey: "emotion", nameEn: "Mimicping", emotion: "모방",
    traits: "'따라하다'에서 온 이름으로 남을 흉내 내고 따라하는 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#7BC86C" },
  { id: "holoping", nameKo: "홀로핑", seasonKey: "emotion", nameEn: "Holoping", emotion: "외로움",
    traits: "'홀로'에서 온 이름으로 외로움과 고독의 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#7C8CA5" },
  { id: "ttokttokping", nameKo: "똑똑핑", seasonKey: "emotion", nameEn: "Ttokttokping", emotion: "똑똑함",
    traits: "'똑똑하다'에서 온 이름으로 영리함과 지식을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#4C7FB0" },
  { id: "ssingssingping", nameKo: "씽씽핑", seasonKey: "emotion", nameEn: "Ssingssingping", emotion: "활력",
    traits: "'씽씽' 달리는 데서 온 이름으로 활력과 빠름을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#3EC6C9" },
  { id: "ahyuping", nameKo: "아휴핑", seasonKey: "emotion", nameEn: "Ahyuping", emotion: "피곤",
    traits: "'아휴' 하는 한숨에서 온 이름으로 피곤함과 지침의 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#9AA0A8" },
  { id: "tteobeolping", nameKo: "떠벌핑", seasonKey: "emotion", nameEn: "Tteobeolping", emotion: "수다",
    traits: "'떠벌리다'에서 온 이름으로 수다스럽게 떠벌리는 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#E58B4A" },
  { id: "noraping-noriping", nameKo: "노라핑&노리핑", seasonKey: "emotion", nameEn: "Noraping & Noriping", emotion: "신남",
    traits: "형 노라핑과 아기 동생 노리핑 형제 티니핑이다. 노라핑은 게임을 좋아하지만 우는 동생을 업어 달래느라 마음껏 놀지 못한다. 노리핑은 5성 최고급 분유만 마시는 까다로운 아기이면서도, 염동력으로 악동핑의 공격을 버텨낼 만큼 힘이 세다.",
    story: "", relations: [], colorHex: "#F2A93B" },
  { id: "deoldeolping", nameKo: "덜덜핑", seasonKey: "emotion", nameEn: "Deoldeolping", emotion: "겁",
    traits: "'덜덜 떨다'에서 온 이름으로 겁먹고 떠는 감정을 상징한다.",
    story: "1기에 등장한 감정 티니핑 중 하나이다.", relations: [], colorHex: "#8FA6C4" },

  /* ---------- 2기 보석 티니핑 ---------- */
  { id: "j-hachuping", nameKo: "다이아 하츄핑", seasonKey: "jewel", nameEn: "Diamond Heartsping", emotion: "사랑",
    traits: "2기에서 다이아몬드 보석을 상징하는 다이아 하츄핑으로 등장하는 기존 로열 티니핑이다. 우정과 깊은 유대를 강조하는 '사랑'을 대표한다.",
    story: "2기부터 로열 티니핑 후보생들의 선생님 역할을 맡아 팀을 이끌고 성장시킨다.",
    relations: [{ id: "joaping", label: "제자" }, { id: "banggeulping", label: "제자" }, { id: "mideoping", label: "제자" }, { id: "dahaeping", label: "라이벌" }], colorHex: "#FF5FA2" },
  { id: "joaping", nameKo: "조아핑", seasonKey: "jewel", nameEn: "Joahping", emotion: "친절",
    traits: "에메랄드를 상징하는 초록빛 로열 티니핑 후보생으로, 마법 붓으로 동물과 교감하고 다룬다. 공감 능력이 뛰어나지만 덜렁대며 사고를 치는 신참이다.",
    story: "로미와 함께 활동하는 로열 후보생으로, 방글핑·믿어핑과 팀을 이루어 정식 로열 티니핑이 된다.",
    relations: [{ id: "banggeulping", label: "팀 동료" }, { id: "mideoping", label: "팀 동료" }, { id: "todakping", label: "단짝" }, { id: "j-hachuping", label: "스승" }], colorHex: "#2ECC71" },
  { id: "banggeulping", nameKo: "방글핑", seasonKey: "jewel", nameEn: "Teeheeping", emotion: "웃음",
    traits: "루비를 상징하는 로열 티니핑 후보생으로, 늘 밝게 웃는 장난꾸러기다. 충동적이고 명랑하며 먼저 행동하는 성격이다.",
    story: "조아핑·믿어핑과 함께 로열 후보생으로 훈련하며, 그 웃음이 종종 친구들에게 힘이 되어 정식 로열핑이 된다.",
    relations: [{ id: "joaping", label: "팀 동료" }, { id: "mideoping", label: "팀 동료" }, { id: "j-hachuping", label: "스승" }], colorHex: "#E0245E" },
  { id: "mideoping", nameKo: "믿어핑", seasonKey: "jewel", nameEn: "Trustping", emotion: "믿음",
    traits: "사파이어를 상징하는 파란빛의 남자 로열 티니핑 후보생으로, 누구든 쉽게 믿는 가장 순수한 성격이다.",
    story: "세 로열 후보생 중 하나로 그 믿음이 갈등 해결의 열쇠가 되곤 하며, 발레핑과 인연을 맺는다.",
    relations: [{ id: "joaping", label: "팀 동료" }, { id: "banggeulping", label: "팀 동료" }, { id: "balleping", label: "인연" }, { id: "j-hachuping", label: "스승" }], colorHex: "#2A6FD6" },
  { id: "dahaeping", nameKo: "다해핑", seasonKey: "key", nameEn: "Onlyping", emotion: "헌신",
    traits: "흑진주를 상징하는 티니핑으로, 가면을 쓴 '가면핑' 모습으로도 등장한다. 왕립 티니핑 학교의 수석 졸업생이다.",
    story: "왕립 학교 시절 하츄핑의 라이벌이었으며, 파트너 제니를 향한 헌신과 열등감 속에서 중간 보스로 등장한다.",
    relations: [{ id: "j-hachuping", label: "라이벌" }], colorHex: "#3B2E5A" },
  { id: "kkareuping", nameKo: "까르핑", seasonKey: "jewel", nameEn: "Tickleping", emotion: "짓궂음",
    traits: "시트린을 상징하는 초록빛 일반 보석 티니핑으로, 마법 깃털 부채로 남을 간지럽히는 것을 좋아하는 장난꾸러기다.",
    story: "보석의 숲에서 지구로 떨어진 뒤 로미에게 캐치되어 이모션 왕국으로 돌아가는 티니핑 중 하나다.",
    relations: [], colorHex: "#7CB342" },
  { id: "ayaping", nameKo: "아야핑", seasonKey: "jewel", nameEn: "Owwping", emotion: "엄살",
    traits: "가넷을 상징하는 붉은빛 일반 보석 티니핑으로, 사소한 아픔도 크게 부풀리는 엄살쟁이다. 마법 반창고로 남도 엄살쟁이로 만든다.",
    story: "보석의 숲을 그리워하며, 지구에 떨어진 뒤 로미에게 캐치되는 티니핑 중 하나다.",
    relations: [], colorHex: "#B7302E" },
  { id: "sowonping", nameKo: "소원핑", seasonKey: "jewel", nameEn: "Wishping", emotion: "소원",
    traits: "보랏빛 일반 보석 티니핑으로, 순수하지만 어설픈 성격이다. 마법 램프에서 소환되어 세 가지 소원을 들어준다.",
    story: "소원을 들어주지만 종종 엉뚱하거나 예상 밖의 방식으로 이뤄지곤 한다.",
    relations: [], colorHex: "#9B6FD4" },
  { id: "todakping", nameKo: "토닥핑", seasonKey: "jewel", nameEn: "Patping", emotion: "위로",
    traits: "비취를 상징하는 초록빛 '위로의 티니핑'으로, 깊은 이해심과 따뜻한 마음을 지녔다. 위로 담요로 실의에 빠진 이를 달랜다.",
    story: "조아핑과 단짝이며, 마법보다 곁에 있어주는 것이 더 큰 위로라고 믿는다.",
    relations: [{ id: "joaping", label: "단짝" }], colorHex: "#3FB68B" },
  { id: "jjokkomping", nameKo: "쪼꼼핑", seasonKey: "jewel", nameEn: "Timidping", emotion: "소심함",
    traits: "연한 하늘빛 일반 보석 티니핑으로, 소심하고 겁이 많다. 숨바꼭질을 좋아하지만 늘 숨어 지내며, 아코디언으로 대상을 작게 만든다.",
    story: "보석의 숲에서 지구로 떨어진 뒤 로미에게 캐치되는 티니핑 중 하나다.",
    relations: [], colorHex: "#8FC9E8" },
  { id: "ssaksakping", nameKo: "싹싹핑", seasonKey: "jewel", nameEn: "Tidyping", emotion: "깔끔함",
    traits: "페리도트를 상징하는 일반 보석 티니핑으로, 더러운 것을 못 참고 늘 청소하는 깔끔쟁이다. 마법 빗자루를 사용한다.",
    story: "귀여운 외모와 달리 집착적인 성격이라, 허락 없이 남의 물건을 정리해 문제를 일으키기도 한다.",
    relations: [], colorHex: "#A6C844" },
  { id: "matnaping", nameKo: "맛나핑", seasonKey: "jewel", nameEn: "Yummyping", emotion: "미각",
    traits: "산호 보석을 상징하는 일반 보석 티니핑으로, 요리를 사랑하며 충청도 사투리를 쓴다. 마법 국자로 요리 실력을 가르쳐 준다.",
    story: "어려움을 겪는 요리사들이 실력을 키우도록 돕는 역할을 한다.",
    relations: [], colorHex: "#FF7F6B" },
  { id: "pogeunping", nameKo: "포근핑", seasonKey: "jewel", nameEn: "Cozyping", emotion: "포근함",
    traits: "문스톤을 상징하는 일반 보석 티니핑으로, 뜨개질을 좋아한다. 마법 바늘로 사물을 포근한 털실 인형으로 바꾼다.",
    story: "친구들과 포근함을 나누려다 하츄핑을 털실 인형으로 만들었다는 오해를 사며 초반 이야기를 이끈다.",
    relations: [], colorHex: "#DCE6F2" },
  { id: "memoping", nameKo: "메모핑", seasonKey: "jewel", nameEn: "Memoping", emotion: "메모",
    traits: "터키석을 상징하는 일반 보석 티니핑으로, 메모하기를 좋아하는 덜렁이다. 마법 다이어리에 쓴 것을 현실로 만든다.",
    story: "장난처럼 능력을 쓰지만 사실 친구들의 관심을 바라는 외로운 티니핑으로, 진정한 우정의 가치를 배운다.",
    relations: [], colorHex: "#3FC8C8" },
  { id: "gongjuping", nameKo: "공쥬핑", seasonKey: "jewel", nameEn: "Ladyping", emotion: "우아함",
    traits: "노란빛의 일반 보석 티니핑으로, 스스로를 공주라 여기며 자신의 왕국을 세우려 한다. 남에게 직책을 부여해 따르게 만든다.",
    story: "우아하게 행동하지만 그 이면에는 순진하고 제멋대로인 면이 있다.",
    relations: [], colorHex: "#F4C733" },
  { id: "jjakjjakping", nameKo: "짝짝핑", seasonKey: "jewel", nameEn: "Buddyping", emotion: "외로움",
    traits: "아쿠아마린을 상징하는 일반 보석 티니핑으로, 짝과 짝수에 집착하는 수다쟁이다. 마법 캐스터네츠로 사물과 생명을 복제한다.",
    story: "정작 자신은 복제하지 못하는 한계 탓에 외로움을 느끼며 남의 물건과 동료를 자꾸 복제한다.",
    relations: [], colorHex: "#6FD6D0" },
  { id: "juneping", nameKo: "주네핑", seasonKey: "jewel", nameEn: "Giftping", emotion: "나눔",
    traits: "토파즈를 상징하는 일반 보석 티니핑으로, 선물하기를 좋아하는 활발하고 명랑한 성격이다. 마법으로 완벽한 선물을 만들어 준다.",
    story: "선물 상자 안에 무엇이 들었는지 자신도 모르지만, 받는 이가 가장 원하는 것이 들어 있다.",
    relations: [], colorHex: "#F2A63B" },
  { id: "ttukttakping", nameKo: "뚝딱핑", seasonKey: "jewel", nameEn: "Sculptping", emotion: "창의력",
    traits: "자수정을 상징하는 일반 보석 티니핑으로, 마법 망치로 조각상을 만들고 생명을 불어넣는 조각가다. 내성적이고 예민하다.",
    story: "하츄핑의 우아함을 본 뒤 그를 동경하게 되며, 창작 열정을 되찾아 걸작을 완성한다.",
    relations: [{ id: "j-hachuping", label: "동경" }], colorHex: "#8E5AC8" },
  { id: "balleping", nameKo: "발레핑", seasonKey: "jewel", nameEn: "Balletping", emotion: "우아함",
    traits: "로즈 쿼츠를 상징하는 분홍빛 일반 보석 티니핑으로, 발레를 사랑하며 우아한 아름다움을 추구한다. 마법 스노볼로 주변에 발레 동작을 불어넣는다.",
    story: "믿어핑과의 인연을 통해 진정한 예술은 완벽한 기교가 아닌 마음에서 온다는 것을 배운다.",
    relations: [{ id: "mideoping", label: "인연" }], colorHex: "#F4A7C4" },
  { id: "wonderping", nameKo: "원더핑", seasonKey: "jewel", nameEn: "Wonderping", emotion: "영웅심",
    traits: "라피스 라줄리를 상징하는 파란빛 일반 보석 티니핑으로, 영웅을 꿈꾸는 용감한 성격이다. 불의를 참지 못하고 어려운 이를 돕는다.",
    story: "자신보다 남의 안전을 우선했을 때 능력이 깨어나, 티니핑 중 최초로 스스로 비행에 성공한다.",
    relations: [], colorHex: "#2B5CA8" },

  /* ---------- 3기 열쇠 티니핑 ---------- */
  { id: "k-hachuping", nameKo: "플로라 하츄핑", seasonKey: "key", nameEn: "Flora Heartsping", emotion: "사랑",
    traits: "시리즈 주인공의 파트너 티니핑으로, 3기에서는 '플로라 하츄핑'이라는 새로운 폼으로 등장한다. 봄과 꽃을 상징하는 로열 티니핑이다.",
    story: "로미와 함께하는 핵심 파트너로서 열쇠 티니핑들을 캐치하는 여정을 이끈다.",
    relations: [{ id: "nanaping", label: "동료 로열핑" }, { id: "kkuraeping", label: "동료 로열핑" }, { id: "soljjiping", label: "동료 로열핑" }, { id: "luckyping", label: "함께하는 레전드핑" }], colorHex: "#F48FB1" },
  { id: "nanaping", nameKo: "나나핑", seasonKey: "key", nameEn: "Nanaping", emotion: "열정",
    traits: "빨간 머리 포니테일에 태양 모양 열쇠를 지닌 로열 티니핑이다. 손거울을 소품으로 사용하며 '열정의 반사' 마법으로 상대의 마법을 되돌리지만, 빛이 없거나 흐린 날씨에는 발동되지 않는다.",
    story: "언제나 자신만만하게 먼저 나서는 성격이지만 체력이 부족해 허당끼를 보이며, 로미의 티니핑 캐치를 돕는다.",
    relations: [{ id: "k-hachuping", label: "동료 로열핑" }, { id: "kkuraeping", label: "동료 로열핑" }, { id: "soljjiping", label: "동료 로열핑" }], colorHex: "#E23A3A" },
  { id: "kkuraeping", nameKo: "꾸래핑", seasonKey: "key", nameEn: "Okeydokeyping", emotion: "평화",
    traits: "땋은 머리에 눈과 얼음을 연상시키는 디자인의 로열 티니핑으로, 마법 눈사람 소품으로 눈덩이를 만들거나 대상을 얼릴 수 있다. 시리즈 최초로 인격이 있는 소품을 가진 티니핑이다.",
    story: "온화하고 배려심이 많으며 평화를 사랑하지만, 화가 나면 강력한 얼음 마법으로 돌변하는 반전 기믹을 가졌다.",
    relations: [{ id: "k-hachuping", label: "동료 로열핑" }, { id: "nanaping", label: "동료 로열핑" }, { id: "soljjiping", label: "동료 로열핑" }], colorHex: "#7FC7E8" },
  { id: "soljjiping", nameKo: "솔찌핑", seasonKey: "key", nameEn: "Soljjiping", emotion: "차분함",
    traits: "흰 머리에 안경을 쓴 남성형 로열 티니핑으로, 가을과 구름을 테마로 한다. 조용하고 차분한 성향이다.",
    story: "필요한 순간에 동료들을 돕는 조력자 역할을 수행하는 3기 로열 티니핑이다.",
    relations: [{ id: "k-hachuping", label: "동료 로열핑" }, { id: "nanaping", label: "동료 로열핑" }, { id: "kkuraeping", label: "동료 로열핑" }], colorHex: "#9DB4CE" },
  { id: "luckyping", nameKo: "행운핑", seasonKey: "key", nameEn: "Luckyping", emotion: "행운",
    traits: "시리즈 사상 최초로 등장한 레전드 등급 티니핑으로, 무지개빛 행운을 상징한다.",
    story: "3기 1화부터 신비한 상자에 갇힌 채 로미 일행에 합류하며, 마스터키를 통해 봉인이 해제된다.",
    relations: [{ id: "k-hachuping", label: "함께하는 로열핑" }, { id: "nanaping", label: "함께하는 로열핑" }], colorHex: "#F2C33E" },
  { id: "ppalliping", nameKo: "빨리핑", seasonKey: "key", nameEn: "Ppalliping", emotion: "신속함",
    traits: "열쇠로 주변 사물로 변신하는 능력을 가진 일반 열쇠 티니핑이다. 이름 그대로 '빠름'을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#FF7A29" },
  { id: "yamyamping", nameKo: "얌얌핑", seasonKey: "key", nameEn: "Yamyamping", emotion: "식욕",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 음식과 먹는 즐거움을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#E9522B" },
  { id: "tteugeoping", nameKo: "뜨거핑", seasonKey: "key", nameEn: "Tteugeoping", emotion: "열기",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 뜨거움과 소방을 연상시키는 테마를 가졌다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [{ id: "ppipoping", label: "응급 관련 동료" }], colorHex: "#E23127" },
  { id: "ppipoping", nameKo: "삐뽀핑", seasonKey: "key", nameEn: "Ppippoping", emotion: "응급",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 사이렌 소리에서 딴 이름처럼 응급·구조 테마를 가졌다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [{ id: "tteugeoping", label: "응급 관련 동료" }], colorHex: "#F26D6D" },
  { id: "ganhoping", nameKo: "간호핑", seasonKey: "key", nameEn: "Ganhoping", emotion: "돌봄",
    traits: "삐뽀핑의 조수 역할을 하는 쌍둥이 자매 티니핑이다. 머리 경광등 색(분홍·노랑·초록·파랑)이 다른 4개체가 등장하지만 이름은 모두 같다. 삐뽀핑을 '선생님'이라 부르며 존댓말을 쓰고 지시에 충실히 따르는데, 오히려 삐뽀핑보다 유능하게 그려진다.",
    story: "", relations: [{ id: "ppipoping", label: "선생님" }], colorHex: "#7FD1AE" },
  { id: "himnaeping", nameKo: "힘내핑", seasonKey: "key", nameEn: "Himnaeping", emotion: "응원",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 격려와 기운 북돋기를 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#F26198" },
  { id: "gochyeoping", nameKo: "고쳐핑", seasonKey: "key", nameEn: "Gochyeoping", emotion: "수리",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 고치고 수리하는 것을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#4E8FC0" },
  { id: "araping", nameKo: "아라핑", seasonKey: "key", nameEn: "Araping", emotion: "열쇠 티니핑",
    traits: "열쇠로 주변 사물로 변신하는 능력을 가진 일반 열쇠 티니핑이다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#6C8FD6" },
  { id: "fashionping", nameKo: "패션핑", seasonKey: "key", nameEn: "Fashionping", emotion: "패션",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 패션과 꾸미기를 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [{ id: "kkumyeoping", label: "꾸미기 관련 동료" }], colorHex: "#C77DD6" },
  { id: "kkomttakping", nameKo: "꼼딱핑", seasonKey: "key", nameEn: "Kkomttakping", emotion: "열쇠 티니핑",
    traits: "열쇠로 주변 사물로 변신하는 능력을 가진 일반 열쇠 티니핑이다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#3F72B0" },
  { id: "pongdangping", nameKo: "퐁당핑", seasonKey: "key", nameEn: "Pongdangping", emotion: "물놀이",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 물과 수영을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#3FB6C4" },
  { id: "partiping", nameKo: "파티핑", seasonKey: "key", nameEn: "Partiping", emotion: "축제",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 파티와 축제 준비를 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#F6B93B" },
  { id: "kkumyeoping", nameKo: "꾸며핑", seasonKey: "key", nameEn: "Kkumyeoping", emotion: "꾸미기",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 외형을 단장하고 꾸미는 것을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [{ id: "fashionping", label: "꾸미기 관련 동료" }], colorHex: "#B06AD1" },
  { id: "ppijimping", nameKo: "삐짐핑", seasonKey: "key", nameEn: "Ppijimping", emotion: "삐짐",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 삐지고 토라지는 감정을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#F084A5" },
  { id: "aaping", nameKo: "아아핑", seasonKey: "key", nameEn: "Aaping", emotion: "열쇠 티니핑",
    traits: "열쇠로 주변 사물로 변신하는 능력을 가진 일반 열쇠 티니핑이다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#7EC8E3" },
  { id: "binggeulping", nameKo: "빙글핑", seasonKey: "key", nameEn: "Binggeulping", emotion: "회전",
    traits: "열쇠로 주변 사물로 변신하는 일반 열쇠 티니핑으로, 빙글빙글 도는 회전을 테마로 한다.",
    story: "3기 에피소드에서 로미 일행과 얽히며 등장하는 캐치 대상 티니핑이다.",
    relations: [], colorHex: "#F2A03D" },

  /* ---------- 4기 디저트 티니핑 ---------- */
  { id: "posilping", nameKo: "포실핑", seasonKey: "dessert", nameEn: "Fluffyping", emotion: "순수함",
    traits: "솜사탕이 모티브인 로열 티니핑으로, 모두에게 다정하고 남을 의심하지 않는 순수한 성격이다. 마법 솜사탕 통과 막대로 다양한 솜사탕을 만들고 솜사탕 구름을 소환해 이동한다.",
    story: "디저트 로열 티니핑 중 하나로 서브 주인공 격이다. 순진함 탓에 종종 사고를 치지만 식욕이 왕성하고 잠을 좋아하는 등 엉뚱한 매력이 있다.",
    relations: [{ id: "malrangping", label: "디저트 로열 동료" }, { id: "shashaping", label: "디저트 로열 동료" }], colorHex: "#F6B8D0" },
  { id: "malrangping", nameKo: "말랑핑", seasonKey: "dessert", nameEn: "Jellyping", emotion: "발랄함",
    traits: "젤리가 모티브이며 이름은 '말랑말랑'에서 왔다. 지치지 않는 에너지의 발랄한 성격이지만 깊이 생각하지 않고 행동하는 엉뚱한 구석이 있다. 몸이 말랑해 팔을 늘리거나 납작해질 수 있고 젤리볼 마법을 쓴다.",
    story: "디저트 로열 티니핑으로 서브 주인공 격이며, 단짝 친구 푸딩핑과 함께 활약한다.",
    relations: [{ id: "puddingping", label: "단짝 친구" }, { id: "shashaping", label: "디저트 로열 동료" }], colorHex: "#F65A6E" },
  { id: "shashaping", nameKo: "샤샤핑", seasonKey: "dessert", nameEn: "Shashaping", emotion: "긍정",
    traits: "아이스크림과 셔벗이 모티브인 로열 티니핑이다. 낙천적이고 남을 깊이 배려하며 늘 따뜻하게 대한다. 마법 콘 모자로 아이스크림 요정들을 부려 공격·지원·방어에 활용한다.",
    story: "디저트 마을 공장에서 샤샤핑의 생산 계획에 따라 티니핑들이 분업해 디저트를 만든다. 차가운 모티브와 달리 따뜻함과 격려를 상징한다.",
    relations: [{ id: "posilping", label: "디저트 로열 동료" }, { id: "iceflakeping", label: "친구" }], colorHex: "#79D2D0" },
  { id: "saekomping", nameKo: "새콤핑", seasonKey: "dessert", nameEn: "Saekomping", emotion: "새콤함",
    traits: "마법 오렌지와 케이크가 모티브인 레전드 티니핑이다. 똑 부러지고 도도하며 새침한 성격으로, 별 모양 새콤 요술봉을 사용한다.",
    story: "행운핑의 뒤를 잇는 4기의 레전드핑으로 달콤핑과 단짝 친구다. 사소한 다툼으로 봉인되며 디저트 마을에 갈등을 일으켰다가 결국 화해한다. 좌우명은 '둘 같은 하나, 하나 같은 둘'.",
    relations: [{ id: "dalkomping", label: "단짝 친구" }], colorHex: "#6DBE45" },
  { id: "dalkomping", nameKo: "달콤핑", seasonKey: "dessert", nameEn: "Dalkomping", emotion: "달콤함",
    traits: "마법 체리와 케이크가 모티브인 레전드 티니핑이다. 상냥하고 여유 넘치는 성격이며, 달콤한 요술봉으로 주변을 달콤하게 만드는 능력을 지녔다.",
    story: "새콤핑과 단짝 친구로 함께 디저트 마을을 돌본다. 자존심을 건 두 티니핑의 다툼이 4기의 핵심 사건이 된다.",
    relations: [{ id: "saekomping", label: "단짝 친구" }], colorHex: "#E23B5A" },
  { id: "candyping", nameKo: "캔디핑", seasonKey: "dessert", nameEn: "Candyping", emotion: "솔깃함",
    traits: "사탕이 모티브인 일반 티니핑이다. 마법으로 대상에게 듣기 좋은 말(사탕발림)을 하는 능력을 지녔다.",
    story: "프린세스 베리하트가 작중 처음으로 캐치한 디저트 티니핑이자, 슈가 프리즘 샷을 맞지 않고 캐치된 최초의 디저트 티니핑이다.",
    relations: [{ id: "waffleping", label: "함께 첫 등장" }], colorHex: "#FF77A9" },
  { id: "meringueping", nameKo: "머랭핑", seasonKey: "dessert", nameEn: "Meringueping", emotion: "장식",
    traits: "머랭이 모티브인 '장식의 티니핑'이다. 마법 거품기로 무엇이든 머랭으로 장식하며, 순수하지만 고집이 있고 밋밋하거나 칙칙한 것을 싫어한다.",
    story: "프린세스 스위트플로스가 캐치한 첫 디저트 티니핑이자, 슈가 프리즘 샷 공격으로 캐치된 최초의 티니핑이다.",
    relations: [], colorHex: "#F5E3BE" },
  { id: "sandping", nameKo: "샌드핑", seasonKey: "dessert", nameEn: "Sandping", emotion: "친밀함",
    traits: "샌드위치 쿠키(크림 샌드 과자)가 모티브다. 마법 주걱으로 빈 곳을 크림으로 채우며, 빈 공간을 메우고 이어붙이는 데 집착한다.",
    story: "샌드 과자를 쪼개 크림만 먹는 것을 몹시 싫어하며, 과자를 온전히 지키는 것을 예의로 여긴다.",
    relations: [], colorHex: "#6E4A32" },
  { id: "donutping", nameKo: "또너핑", seasonKey: "dessert", nameEn: "Donutping", emotion: "명랑함",
    traits: "도넛이 모티브이며, 이름은 '도넛'의 아기 말투에서 왔다. 다른 티니핑보다 작고 어려 보이지만 아기 취급을 싫어하고 칭찬을 원한다. '홀 펀치' 마법으로 사물에 동그란 구멍을 낸다.",
    story: "로열 티니핑이 되고 싶어하는 최초의 티니핑으로 성장 서사를 가진다. 커핑&머핑을 돌보는 보호자 역할을 한다.",
    relations: [{ id: "keoping-meoping", label: "돌봄(보호자)" }], colorHex: "#F49BB0" },
  { id: "hotcakeping", nameKo: "핫케핑", seasonKey: "dessert", nameEn: "Hotcakeping", emotion: "성취감",
    traits: "핫케이크(팬케이크)가 모티브다. 마음이 따뜻해 남을 돕기 좋아하며, 무언가를 차곡차곡 쌓는 데서 성취감을 느끼고 어지러진 것을 싫어한다. 마법 프라이팬으로 물건을 가지런히 쌓는다.",
    story: "1화에 등장한 일반 디저트 티니핑으로, 소년 딜런에게 마법 대신 올바른 쌓기 기술을 가르치며 정직함을 강조했다.",
    relations: [{ id: "waffleping", label: "자주 함께 등장" }], colorHex: "#F2B646" },
  { id: "waffleping", nameKo: "와플핑", seasonKey: "dessert", nameEn: "Waffleping", emotion: "납작함",
    traits: "와플이 모티브인 '납작함의 티니핑'이다. 성격이 급하고 장난기가 많으며 가만히 있는 것을 못 견딘다. 마법 심벌즈로 무엇이든 종이처럼 납작하게 만든다.",
    story: "디저트 공장에서 실제로 일하는 유일한 남성 티니핑이다. 데뷔 에피소드에서 프린세스 젤리스틴에게 캐치되었다.",
    relations: [{ id: "candyping", label: "함께 첫 등장" }, { id: "hotcakeping", label: "자주 함께 등장" }], colorHex: "#C6873A" },
  { id: "macaping", nameKo: "마카핑", seasonKey: "dessert", nameEn: "Macaping", emotion: "화려함",
    traits: "마카롱이 모티브다. 밝고 단순한 성격에 종종 제멋대로 행동하며, 알록달록한 것과 색을 바꾸는 것을 좋아하고 단조롭거나 칙칙한 색을 싫어한다. 마법 짤주머니로 사물의 색을 바꾼다.",
    story: "색을 바꾸는 능력으로 주변을 화려하게 물들이는 일반 디저트 티니핑이다.",
    relations: [], colorHex: "#F28FB8" },
  { id: "lolliping", nameKo: "롤리핑", seasonKey: "dessert", nameEn: "Lolliping", emotion: "장난기",
    traits: "막대사탕(롤리팝)이 모티브다. 순진해서 사고를 치지만 마음은 따뜻하며, 빙글빙글 돌리는 것을 좋아한다. 바람개비로 사물을 회전시키거나 어지럽게 만든다.",
    story: "디저트 공장에서 컨베이어 벨트의 방향을 바꾸는 역할을 맡는 일반 디저트 티니핑이다.",
    relations: [], colorHex: "#E85AA0" },
  { id: "keoping-meoping", nameKo: "커핑&머핑", seasonKey: "dessert", nameEn: "Cupping & Muffping", emotion: "호기심",
    traits: "컵케이크(커핑)와 머핀(머핑)이 모티브인 아기 쌍둥이로 하나의 큐브를 공유한다. 활발하고 호기심 많은 장난꾸러기이며 늘 붙어 다닌다. 울면 몸이 커지고 웃으면 원래 크기로 돌아온다.",
    story: "시리즈 최초의 쌍둥이이자 남매 티니핑으로, 14화에서 처음 등장했다. 말을 하지 않고 아기 소리만 낸다.",
    relations: [{ id: "donutping", label: "보호자" }], colorHex: "#F3C1D8" },
  { id: "puddingping", nameKo: "푸딩핑", seasonKey: "dessert", nameEn: "Puddingping", emotion: "여림",
    traits: "푸딩이 모티브다. 수줍고 쉽게 풀이 죽지만 음악과 춤을 사랑하는 열정적인 티니핑이다. '신나는 푸딩 댄스' 마법으로 흥겨운 음악을 들은 이들을 저절로 춤추게 만든다.",
    story: "19화에 등장했으며, 단짝 친구 말랑핑과의 우정을 통해 자신감을 얻는 성장 서사를 가진다.",
    relations: [{ id: "malrangping", label: "단짝 친구" }], colorHex: "#E7B84E" },
  { id: "iceflakeping", nameKo: "눈꽃핑", seasonKey: "dessert", nameEn: "Iceflakeping", emotion: "천진난만함",
    traits: "눈꽃빙수·팥빙수가 모티브다. 천진난만하면서도 다소 내성적인 면이 있다. 눈과 얼음 마법으로 눈을 내리거나 얼음을 만들며, 나중에는 능력을 눈에만 한정하도록 정교하게 다룬다.",
    story: "자택에서 빙수를 만드는 일반 디저트 티니핑이다. 슈가 프리즘 샷이 아닌 스스로의 의지로 합류한 티니핑이며 샤샤핑과 친해진다.",
    relations: [{ id: "shashaping", label: "친구" }], colorHex: "#BBE1F0" },
  { id: "chocoping", nameKo: "쪼꼬핑", seasonKey: "dessert", nameEn: "Chocoping", emotion: "화해",
    traits: "구슬형 초콜릿이 모티브다. 다정하고 활발하며 다투는 친구들을 화해시키는 데 열심이다. 마법 '초코 모자'로 대상의 머리 모양을 바꿔 사이좋게 만들며, 초코볼을 던져 공격하기도 한다.",
    story: "21화에 등장했다. 처음에는 마을 사람들의 갈등을 풀어주다가 점차 더 복잡한 사건에 얽히며 후반부 전개에 기여한다.",
    relations: [], colorHex: "#7A4A28" },
  { id: "melloping", nameKo: "멜로핑", seasonKey: "dessert", nameEn: "Melloping", emotion: "폭신함",
    traits: "마시멜로가 모티브다. 친절하고 상냥하지만 눈치가 없는 면이 있다. '폭신폭신 마시멜로' 마법으로 사물과 주변을 부드럽고 포근하게 만들며, 딱딱하고 차가운 것과 높은 곳을 싫어한다.",
    story: "20화에 등장한 일반 디저트 티니핑으로, 마시멜로 인형 '마시멜로롱'을 아낀다.",
    relations: [], colorHex: "#F7D4DF" },
  { id: "yogurtping", nameKo: "요거핑", seasonKey: "dessert", nameEn: "Yogurtping", emotion: "편안함",
    traits: "베리를 올린 요거트가 모티브다. 남의 안녕을 살피는 배려심 많은 티니핑으로, 마법 숟가락과 주문으로 편안한 잠을 유도하고 소화를 돕는다. 두 마리의 요거트 양을 데리고 다닌다.",
    story: "'편안함의 티니핑'으로, 양을 세어 잠드는 방식에서 착안해 사람들을 편히 쉬게 돕는다.",
    relations: [], colorHex: "#F0E4E9" },
  /* ---------- 극장판 ---------- */
  { id: "trueoping", nameKo: "트러핑", seasonKey: "movie", nameEn: "Trouping", emotion: "외로움",
    traits: "라미엔느 왕국 왕자 리암의 짝꿍이었던 남성 티니핑이다. 본래 하늘색 몸에 이마에 하얀 하트 무늬가 있었지만, 흑화한 뒤에는 몸이 어두운 보라색으로 바뀌고 이마 무늬도 번개 모양이 된다. 다른 티니핑을 괴물로 만들거나 자기 말만 듣는 병사핑으로 세뇌하는 강한 마법을 쓴다.",
    story: "", relations: [], colorHex: "#7E5BB5" },
  { id: "bangulping", nameKo: "방울핑", seasonKey: "movie", nameEn: "Bangulping", emotion: "활기",
    traits: "지기 싫어하고 활발한 매력이 가득한 바다 티니핑으로, 귀여운 양갈래 머리를 하고 있다. 조개 캐스터네츠를 연주하면 방울 무리가 나와 몸을 지켜 주고 물속에서도 숨을 쉴 수 있게 해 준다. 퐁당핑처럼 다리 대신 인어 꼬리가 있고, 육지에 나오면 다리가 생긴다.",
    story: "", relations: [{ id: "chalrangping", label: "바다 동료" }, { id: "soraping", label: "바다 동료" }], colorHex: "#00DCFF" },
  { id: "chalrangping", nameKo: "찰랑핑", seasonKey: "movie", nameEn: "Chalrangping", emotion: "여유",
    traits: "차분하고 온화하며 찰랑이는 파도처럼 여유로운 바다 티니핑이다. 찰랑거리는 머릿결이 특징이고, 파도 부채를 휘둘러 마법의 파도를 불러낸다. 고래의 말을 사람이 알아들을 수 있게 통역해 줘서 '고래 통역사'라고도 불린다.",
    story: "", relations: [{ id: "bangulping", label: "바다 동료" }, { id: "soraping", label: "바다 동료" }], colorHex: "#FF496A" },
  { id: "soraping", nameKo: "소라핑", seasonKey: "movie", nameEn: "Soraping", emotion: "침착함",
    traits: "바다의 소리를 전해 주는 티니핑으로, 침착하고 느긋한 성격이다. 신비한 소라고동을 불어 바다 친구들을 불러내는 특별한 능력을 가졌다. 분홍색 머리에 인어 꼬리를 달고 있어 퐁당핑과 닮은 점이 많다.",
    story: "", relations: [{ id: "bangulping", label: "바다 동료" }, { id: "chalrangping", label: "바다 동료" }], colorHex: "#FF8BC6" },

  { id: "puffping", nameKo: "뿌뿌핑", seasonKey: "dessert", nameEn: "Puffping", emotion: "흥미",
    traits: "풍선껌이 모티브인 '흥미의 티니핑'이다. 겉으로는 장난기 많은 말썽꾸러기지만 깊은 마음의 상처를 숨긴 이중적인 면이 있다.",
    story: "디저트 마을의 주민이자 4기의 메인 빌런이다. 외로움과 소외감에서 비롯된 집착으로 각성 단계를 거치며 마을 전체를 위협하는 최종 보스가 된다.",
    relations: [], colorHex: "#FF3D8B" }
];
